[package]
name = "berzifetch-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "berzifetch"
path = "src/main.rs"

[dependencies]
colored = "2.1.0"
figlet-rs = "0.1.5"
libc = "0.2.155"
regex = "1.10.4"
users = "0.11"
